FROM alpine:3.22.1 AS builder

COPY ./bin/bacliup /fs/usr/local/bin/
COPY ./docker/fs/ /fs/

RUN chmod 700 /fs/bacliup /fs/bacliup/.config /fs/bacliup/.config/rclone && \
    chmod 600 /fs/bacliup/.config/rclone/rclone.conf

FROM alpine:3.22.1

ENV BACLIUP_CRON_SCRIPT="/usr/local/bin/with-env /usr/local/bin/bacliup"

RUN mkdir -p /var/run/bacliup/environment && \
    apk add --no-cache bash busybox-suid curl gettext gnupg jq pv && \
