#!/usr/bin/env bash
set -e

function build_dockerfile() {
  local variant="$1"

  local dockerfile="Dockerfile"
  if [[ "$variant" != "none" ]]; then
    dockerfile="${dockerfile}.${variant}"
  fi

  cat "${dockerfile_header}" "${docker_dir}/Dockerfile.${variant:-none}" "${dockerfile_footer}" > "$dockerfile"
}

docker_dir="docker"
dockerfile_header="docker/Dockerfile.header"
dockerfile_footer="docker/Dockerfile.footer"

for variant in none postgresql sqlite; do
  echo "Building Dockerfile for variant: $variant"
  build_dockerfile "$variant"
done
