# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build

on:
  push:
    branches:
      - "**/*"
  schedule:
    # Minute (0-59), Hour (0-23), Day of the month (1-31), Month of the Year (1-12), Day of the week (0-6, 0 = Sunday)
    - cron: "0 6 * * 1"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build the Docker image
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: |
          docker build -t alphahydrae/bacliup .

  test:
    runs-on: ubuntu-20.04
    name: Run automated tests
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Install asdf
        uses: asdf-vm/actions/setup@v1
        with:
          asdf_branch: v0.10.2

      - name: Install Bats with asdf
        run: |
          asdf plugin add bats
          asdf install bats

      - name: Run the automated test suite
        run: |
          make check
